version: "3.9"

services:
  postgres:
    image: postgres:16
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: seatlock
      POSTGRES_PASSWORD: seatlock
      POSTGRES_DB: seatlock
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U seatlock"]
      interval: 5s
      timeout: 3s
      retries: 10

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  seatlock:
    build: .
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/seatlock
      SPRING_DATASOURCE_USERNAME: seatlock
      SPRING_DATASOURCE_PASSWORD: seatlock
      SPRING_DATA_REDIS_HOST: redis
      SPRING_DATA_REDIS_PORT: "6379"
      SEATLOCK_JWT_SECRET: "change-this-secret-to-at-least-32-characters-long-random-string"
      SEATLOCK_JWT_EXPIRATION_MINUTES: "60"
      SEATLOCK_HOLDS_TTL_MINUTES: "8"
      SPRING_PROFILES_ACTIVE: prod
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started

volumes:
  postgres_data: